/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.dimed.app;

import br.com.dimed.list.LinkedList;

import static br.com.dimed.utilities.StringUtils.join;
import static br.com.dimed.utilities.StringUtils.split;
import static br.com.dimed.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
